name: CI

on:
  push:
  pull_request:
jobs:
  cibuild:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest --optimize-autoloader      
      - name: Install NPM dependencies
        run: npm install      
      - name: Compile assets
        run: npm run production
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
   #   - name: Execute the PHP lint script 🧹
   #     run: |
   #       ./vendor/bin/phpstan --version
   #       ./vendor/bin/phpstan analyse
#
      - name: Run security checks 👮
        uses: symfonycorp/security-checker-action@v3
        
      - name: Remove .env
        run: rm .env
        
      - name: Build project
        run:  mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -X -r build/giftlist.zip . -x *.git* -x .github/\*  -x node_modules/\* .* "*/\.*"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: giftlist
            path: build/giftlist.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/giftlist.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload logs on build failure 🪵
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Laravel Logs
          path: ./storage/logs
